### ISSUE TITLE
Where and how put  jtag_hw_microsoft_catapult.dll ?

### ISSUE THREAD

**Issue by warchiefmarkus** [dengjingjing/Microsoft-FPGA-Catapult-#2]
Hello ! Can you please explain what purpose is jtag_hw_microsoft_catapult.dll (is it driver ?) where put it ? (bin64 dir of Quartus?) In Quartus Standard 23.1 Device Manager detect Microsoft Catapult Blaster (after connect onboard usb-b to pc) and Stratix-V, so do I still need put jtag_hw_microsoft_catapult.dll somewhere or not ?

**Comment by dengjingjing** [comment]
Quartus.exe
